volumes:
  # hoprd node id files, which should be kept between restarts to not change
  # peer ids all the time
  pluto-data:

x-relay-service: &relay
  image: ${RELAY_IMAGE:-gcr.io/hoprassociation/hopr-rpc-relay:${RELAY_VERSION:-latest}}
  restart: unless-stopped
  depends_on:
    - pluto
  entrypoint: ["/bin/wait-for", "pluto:$${HOPRD_API_PORT}", "-q", "-t", "60", "--", "/sbin/tini", "--"]

services:
  pluto:
    image: gcr.io/hoprassociation/hopr-pluto:valencia
    restart: unless-stopped
    volumes:
      - pluto-data:/tmp
    ports:
      # mapping admin and api ports to localhost for app developers to access
      # the admin UI more easily
      - "13301-13305:13301-13305"
      - "19501-19505:19501-19505"
    environment:
      - DEBUG="${DEBUG}"
      - HOPRD_API_TOKEN="${HOPRD_API_TOKEN}"
  relay-1:
    <<: *relay
    environment:
      - DEBUG="${DEBUG}"
      - ENTRY_PORT=${RELAY_ENTRY_PORT}
      - USE_AUTO_PATHFINDING=${RELAY_USE_AUTO_PATHFINDING:-false}
      - HOPRD_API_PORT=13301
      - HOPRD_API_ENDPOINT=http://pluto:$${HOPRD_API_PORT}
      - HOPRD_API_TOKEN="${HOPRD_API_TOKEN}"
    ports:
      - "9001:8081" # mapping port to localhost for easier recognition
  relay-2:
    <<: *relay
    environment:
      - DEBUG="${DEBUG}"
      - ENTRY_PORT=${RELAY_ENTRY_PORT}
      - USE_AUTO_PATHFINDING=${RELAY_USE_AUTO_PATHFINDING:-false}
      - HOPRD_API_PORT=13302
      - HOPRD_API_ENDPOINT=http://pluto:$${HOPRD_API_PORT}
      - HOPRD_API_TOKEN="${HOPRD_API_TOKEN}"
    ports:
      - "9002:8081" # mapping port to localhost for easier recognition
  relay-3:
    <<: *relay
    environment:
      - DEBUG="${DEBUG}"
      - ENTRY_PORT=${RELAY_ENTRY_PORT}
      - USE_AUTO_PATHFINDING=${RELAY_USE_AUTO_PATHFINDING:-false}
      - HOPRD_API_PORT=13303
      - HOPRD_API_ENDPOINT=http://pluto:$${HOPRD_API_PORT}
      - HOPRD_API_TOKEN="${HOPRD_API_TOKEN}"
    ports:
      - "9003:8081" # mapping port to localhost for easier recognition
  relay-4:
    <<: *relay
    environment:
      - DEBUG="${DEBUG}"
      - ENTRY_PORT=${RELAY_ENTRY_PORT}
      - USE_AUTO_PATHFINDING=${RELAY_USE_AUTO_PATHFINDING:-false}
      - HOPRD_API_PORT=13304
      - HOPRD_API_ENDPOINT=http://pluto:$${HOPRD_API_PORT}
      - HOPRD_API_TOKEN="${HOPRD_API_TOKEN}"
    ports:
      - "9004:8081" # mapping port to localhost for easier recognition
  relay-5:
    <<: *relay
    environment:
      - DEBUG="${DEBUG}"
      - ENTRY_PORT=${RELAY_ENTRY_PORT}
      - USE_AUTO_PATHFINDING=${RELAY_USE_AUTO_PATHFINDING:-false}
      - HOPRD_API_PORT=13305
      - HOPRD_API_ENDPOINT=http://pluto:$${HOPRD_API_PORT}
      - HOPRD_API_TOKEN="${HOPRD_API_TOKEN}"
    ports:
      - "9005:8081" # mapping port to localhost for easier recognition
